server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.135.104:3306/dotware_test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root#dev88
  application:
    name: cloud-service

mybatis:
  mapper-locations: classpath:mapper/*.xml
file:
  location: D:/
logging:
  config: D:/demo1/demo/src/main/resources/logback-spring-xml
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
